version: '3.9'

services:

  postgresDB:
    container_name: postgresDB
    image: postgres
    restart: always
    env_file:    
      - ./.env
    environment:
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_DB: $POSTGRES_DB
    ports:
      - $POSTGRES_PORT:$POSTGRES_PORT
    volumes:
      - pgdata:/var/lib/posgresql
  
  app-node: 
    container_name: app-node
    build: .
    depends_on:
      - postgresDB
    links:
      - postgresDB 
    ports:
      - $NODE_PORT:$NODE_PORT
    volumes:
      - ./src:/app/src

volumes:
  pgdata:
